# Generated by Django 6.1.1 on 2026-09-13 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gems_username',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
