# Generated by Django 6.1.1 on 2026-09-14 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='gems_username',
        ),
    ]
