# Generated by Django 6.1.1 on 2026-09-14 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_remove_profile_gems_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_streak_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='pending_classes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
