# Generated by Django 6.1.1 on 2026-09-17 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_profile_last_streak_date_profile_pending_classes'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='challenge_type',
            field=models.CharField(choices=[('streak_3', '3-Day Streak'), ('streak_7', '7-Day Streak'), ('overall_75', '75% Club'), ('overall_80', '80% Club'), ('perfect_week', 'Perfect Week'), ('subject_saver', 'Subject Saver'), ('custom', 'Custom Challenge')], default='custom', max_length=50),
        ),
        migrations.AddField(
            model_name='challenge',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='challenge',
            name='target',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='userchallenge',
            name='baseline_attended',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userchallenge',
            name='baseline_total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userchallenge',
            name='progress',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='userchallenge',
            name='subject_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userchallenge',
            name='target',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='userchallenge',
            name='xp_awarded',
            field=models.BooleanField(default=False),
        ),
    ]
